In [9]:
import pandas as pd

autos = pd.read_csv('autos.csv', encoding='Latin-1')

In [10]:
import pandas as pd

autos= pd.read_csv("autos.csv", encoding="latin-1")

In [11]:
import pandas as pd

autos= pd.read_csv("autos.csv", encoding="latin-1")

In [12]:
import pandas as pd

autos = pd.read_csv("autos.csv", encoding="latin-1")

In [13]:
autos.head()
autos.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   dateCrawled          371528 non-null  str
 1   name                 371528 non-null  str
 2   seller               371528 non-null  str
 3   offerType            371528 non-null  str
 4   price                371528 non-null  int64
 5   abtest               371528 non-null  str
 6   vehicleType          333659 non-null  str
 7   yearOfRegistration   371528 non-null  int64
 8   gearbox              351319 non-null  str
 9   powerPS              371528 non-null  int64
 10  model                351044 non-null  str
 11  kilometer            371528 non-null  int64
 12  monthOfRegistration  371528 non-null  int64
 13  fuelType             338142 non-null  str
 14  brand                371528 non-null  str
 15  notRepairedDamage    299468 non-null  str
 16  dateCreated          371528 non-null  str
 17  nrOfPictures         371528 non-null  int64
 18  postalCode           371528 non-null  int64
 19  lastSeen             371528 non-null  str
dtypes: int64(7), str(13)
memory usage: 56.7 MB

In [14]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'kilometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='str')

In [15]:
import re

In [16]:
re.sub(r"([a-z])([A-Z])", r"\1_\2", "yearOfRegistration").lower()

'year_of_registration'

In [17]:
autos.columns = [re.sub(r"([a-z])([A-Z])", r"\1_\2", col).lower() for col in autos.columns]

In [18]:
autos.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   date_crawled           371528 non-null  str
 1   name                   371528 non-null  str
 2   seller                 371528 non-null  str
 3   offer_type             371528 non-null  str
 4   price                  371528 non-null  int64
 5   abtest                 371528 non-null  str
 6   vehicle_type           333659 non-null  str
 7   year_of_registration   371528 non-null  int64
 8   gearbox                351319 non-null  str
 9   power_ps               371528 non-null  int64
 10  model                  351044 non-null  str
 11  kilometer              371528 non-null  int64
 12  month_of_registration  371528 non-null  int64
 13  fuel_type              338142 non-null  str
 14  brand                  371528 non-null  str
 15  not_repaired_damage    299468 non-null  str
 16  date_created           371528 non-null  str
 17  nr_of_pictures         371528 non-null  int64
 18  postal_code            371528 non-null  int64
 19  last_seen              371528 non-null  str
dtypes: int64(7), str(13)
memory usage: 56.7 MB

In [19]:
autos = autos.rename(columns={
    "year_of_registration": "registration_year",
    "kilometer": "odometer_km",
})

In [20]:
autos.nunique()

date_crawled             280500
name                     233531
seller                        2
offer_type                    2
price                      5597
abtest                        2
vehicle_type                  8
registration_year           155
gearbox                       2
power_ps                    794
model                       251
odometer_km                  13
month_of_registration        13
fuel_type                     7
brand                        40
not_repaired_damage           2
date_created                114
nr_of_pictures                1
postal_code                8150
last_seen                182806
dtype: int64

In [22]:
print(autos['seller'].value_counts())
print(autos['offer_type'].value_counts())
print(autos['abtest'].value_counts())

seller
privat        371525
gewerblich         3
Name: count, dtype: int64
offer_type
Angebot    371516
Gesuch         12
Name: count, dtype: int64
abtest
test       192585
control    178943
Name: count, dtype: int64

In [23]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,month_of_registration,fuel_type,brand,not_repaired_damage,date_created,nr_of_pictures,postal_code,last_seen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

In [24]:

autos = autos[autos['offer_type'] == 'Angebot']

In [27]:
autos.columns

Index(['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_ps', 'model',
       'odometer_km', 'month_of_registration', 'fuel_type', 'brand',
       'not_repaired_damage', 'date_created', 'nr_of_pictures', 'postal_code',
       'last_seen'],
      dtype='str')

In [29]:
autos = autos.drop(["nr_of_pictures", "seller", "offer_type", "abtest"], axis=1)

In [31]:
autos.shape

(371516, 16)

In [35]:
print(autos['vehicle_type'].value_counts())
print(autos['gearbox'].value_counts())
print(autos['not_repaired_damage'].value_counts())
print(autos['fuel_type'].value_counts())

vehicle_type
limousine     95894
kleinwagen    80021
kombi         67564
bus           30199
cabrio        22898
coupe         19014
suv           14707
andere         3357
Name: count, dtype: int64
gearbox
manuell      274208
automatik     77105
Name: count, dtype: int64
not_repaired_damage
nein    263178
ja       36284
Name: count, dtype: int64
fuel_type
benzin     223854
diesel     107744
lpg          5378
cng           571
hybrid        278
andere        208
elektro       104
Name: count, dtype: int64

In [36]:
autos["gearbox"] = autos["gearbox"].replace({"manuell": "manual", "automatik": "automatic"})

In [37]:
autos["vehicle_type"] = autos["vehicle_type"].replace({"limousine": "sedan", "kleinwagen": "small car", "kombi": "station wagon", "cabrio": "convertible", "andere": "other"})

In [38]:
print(autos['vehicle_type'].value_counts())
print(autos['gearbox'].value_counts())

vehicle_type
sedan            95894
small car        80021
station wagon    67564
bus              30199
convertible      22898
coupe            19014
suv              14707
other             3357
Name: count, dtype: int64
gearbox
manual       274208
automatic     77105
Name: count, dtype: int64

In [39]:
autos = autos.rename(columns={"not_repaired_damage": "has_unrepaired_damage"})

In [41]:
autos["has_unrepaired_damage"] = autos["has_unrepaired_damage"].replace({"nein": "no", "ja": "yes"})

In [42]:
autos["fuel_type"] = autos["fuel_type"].replace({"benzin": "petrol", "elektro": "electric", "andere": "other"})

In [44]:
print(autos['vehicle_type'].value_counts())
print(autos['gearbox'].value_counts())
print(autos['has_unrepaired_damage'].value_counts())
print(autos['fuel_type'].value_counts())

vehicle_type
sedan            95894
small car        80021
station wagon    67564
bus              30199
convertible      22898
coupe            19014
suv              14707
other             3357
Name: count, dtype: int64
gearbox
manual       274208
automatic     77105
Name: count, dtype: int64
has_unrepaired_damage
no     263178
yes     36284
Name: count, dtype: int64
fuel_type
petrol      223854
diesel      107744
lpg           5378
cng            571
hybrid         278
other          208
electric       104
Name: count, dtype: int64

In [46]:

autos.head()

,date_crawled,name,price,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,month_of_registration,fuel_type,brand,has_unrepaired_damage,date_created,postal_code,last_seen
0,2016-03-24 11:52:17,Golf_3_1.6,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN,2016-03-24 00:00:00,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,18300,coupe,2011,manual,190,NaN,125000,5,diesel,audi,yes,2016-03-24 00:00:00,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",9800,suv,2004,automatic,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,1500,small car,2001,manual,75,golf,150000,6,petrol,volkswagen,no,2016-03-17 00:00:00,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,3600,small car,2008,manual,69,fabia,90000,7,diesel,skoda,no,2016-03-31 00:00:00,60437,2016-04-06 10:17:21

In [47]:
autos["date_crawled"] = pd.to_datetime(autos["date_crawled"])

In [48]:
autos['date_created'] = pd.to_datetime(autos['date_created'])
autos['last_seen'] = pd.to_datetime(autos['last_seen'])

In [49]:
autos.info()

<class 'pandas.DataFrame'>
Index: 371516 entries, 0 to 371527
Data columns (total 16 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   date_crawled           371516 non-null  datetime64[us]
 1   name                   371516 non-null  str
 2   price                  371516 non-null  int64
 3   vehicle_type           333654 non-null  str
 4   registration_year      371516 non-null  int64
 5   gearbox                351313 non-null  str
 6   power_ps               371516 non-null  int64
 7   model                  351035 non-null  str
 8   odometer_km            371516 non-null  int64
 9   month_of_registration  371516 non-null  int64
 10  fuel_type              338137 non-null  str
 11  brand                  371516 non-null  str
 12  has_unrepaired_damage  299462 non-null  str
 13  date_created           371516 non-null  datetime64[us]
 14  postal_code            371516 non-null  int64
 15  last_seen              371516 non-null  datetime64[us]
dtypes: datetime64[us](3), int64(6), str(7)
memory usage: 48.2 MB

In [50]:
autos.describe()

,date_crawled,price,registration_year,power_ps,odometer_km,month_of_registration,date_created,postal_code,last_seen
count,371516,3.715160e+05,371516.000000,371516.000000,371516.000000,371516.000000,371516,371516.000000,371516
mean,2016-03-21 13:30:31.646174,1.729558e+04,2004.578164,115.552130,125619.690673,5.734555,2016-03-20 19:42:51.694355,50820.754880,2016-03-30 03:38:01.198492
min,2016-03-05 14:06:22,0.000000e+00,1000.000000,0.000000,5000.000000,0.000000,2014-03-10 00:00:00,1067.000000,2016-03-05 14:15:08
25%,2016-03-13 12:51:46.500000,1.150000e+03,1999.000000,70.000000,125000.000000,3.000000,2016-03-13 00:00:00,30459.000000,2016-03-23 11:36:06.750000
50%,2016-03-21 18:36:22,2.950000e+03,2003.000000,105.000000,150000.000000,6.000000,2016-03-21 00:00:00,49610.000000,2016-04-03 23:17:22
75%,2016-03-29 14:49:34.750000,7.200000e+03,2008.000000,150.000000,150000.000000,9.000000,2016-03-29 00:00:00,71546.000000,2016-04-06 10:45:02
max,2016-04-07 14:36:58,2.147484e+09,9999.000000,20000.000000,150000.000000,12.000000,2016-04-07 00:00:00,99998.000000,2016-04-07 14:58:51
std,NaN,3.588012e+06,92.868077,192.141895,40110.814656,3.712372,NaN,25799.143633,NaN

In [51]:
pd.set_option('display.float_format', '{:,.2f}'.format)

In [52]:
autos.describe()

,date_crawled,price,registration_year,power_ps,odometer_km,month_of_registration,date_created,postal_code,last_seen
count,371516,"371,516.00","371,516.00","371,516.00","371,516.00","371,516.00",371516,"371,516.00",371516
mean,2016-03-21 13:30:31.646174,"17,295.58","2,004.58",115.55,"125,619.69",5.73,2016-03-20 19:42:51.694355,"50,820.75",2016-03-30 03:38:01.198492
min,2016-03-05 14:06:22,0.00,"1,000.00",0.00,"5,000.00",0.00,2014-03-10 00:00:00,"1,067.00",2016-03-05 14:15:08
25%,2016-03-13 12:51:46.500000,"1,150.00","1,999.00",70.00,"125,000.00",3.00,2016-03-13 00:00:00,"30,459.00",2016-03-23 11:36:06.750000
50%,2016-03-21 18:36:22,"2,950.00","2,003.00",105.00,"150,000.00",6.00,2016-03-21 00:00:00,"49,610.00",2016-04-03 23:17:22
75%,2016-03-29 14:49:34.750000,"7,200.00","2,008.00",150.00,"150,000.00",9.00,2016-03-29 00:00:00,"71,546.00",2016-04-06 10:45:02
max,2016-04-07 14:36:58,"2,147,483,647.00","9,999.00","20,000.00","150,000.00",12.00,2016-04-07 00:00:00,"99,998.00",2016-04-07 14:58:51
std,NaN,"3,588,011.69",92.87,192.14,"40,110.81",3.71,NaN,"25,799.14",NaN

In [54]:
display(autos["price"].value_counts().sort_index().head(20))
display(autos["price"].value_counts().sort_index().tail(20))

price
0     10772
1      1189
2        12
3         8
4         1
5        26
7         3
8         9
9         8
10       84
11        5
12        8
13        7
14        5
15       27
16        2
17        5
18        3
19        3
20       51
Name: count, dtype: int64

price
1234566        1
1250000        2
1300000        1
1600000        2
2795000        1
2995000        1
3890000        1
3895000        1
9999999        3
10000000       8
10010011       1
11111111      10
12345678       9
14000500       1
27322222       1
32545461       1
74185296       1
99000000       1
99999999      15
2147483647     1
Name: count, dtype: int64

In [56]:
print((autos["price"] < 100).sum())
print((autos["price"] < 500).sum())
print((autos["price"] < 1000).sum())

13314
36055
83327

In [61]:
autos["price"].value_counts().sort_index().head(100)

price
0      10772
1       1189
2         12
3          8
4          1
5         26
7          3
8          9
9          8
10        84
11         5
12         8
13         7
14         5
15        27
16         2
17         5
18         3
19         3
20        51
21         1
24         1
25        33
26         1
27         1
29         2
30        55
32         1
33         1
35        18
38         1
39         6
40        45
45        16
47         1
49        12
50       327
55        20
58         1
59         6
60        58
65        19
66         2
69         3
70        69
74         1
75        54
77         1
79         4
80       146
85        11
88         1
89         3
90        41
95        13
98         2
99       109
100     1032
101        4
105        3
106        1
108        1
110       35
111       15
112        1
115        4
117        4
119        4
120      240
121        1
122        3
123        3
125       51
126        1
127        1
128        1
129        7
130       96
132        1
133        1
135       10
139        4
140       46
142        1
145        6
149       40
150     1609
155        9
156        3
157        1
158        1
159        4
160       66
162        1
165        4
166        1
169        5
170       85
173        1
175       61
Name: count, dtype: int64

In [60]:
autos["price"].value_counts().sort_index().tail(100)

price
189981         1
190000         1
192500         2
194000         1
195000         3
195900         1
197000         1
197500         1
198000         1
199900         1
200000         2
205000         2
208250         1
214800         1
219000         2
220000         1
224000         1
225000         5
229000         1
229900         1
230000         3
233000         1
235000         1
237500         1
238000         1
239000         1
245000         1
249000         1
250000         4
254900         1
257500         1
258000         1
259000         1
260000         3
265000         1
270000         1
275000         1
279000         1
284000         1
285000         1
294900         1
295000         1
299000         3
300000         1
323223         1
345000         1
349000         1
350000         4
368000         1
370000         2
390000         1
395000         1
399997         1
420000         1
440000         1
445000         1
466000         1
485000         1
487000         1
488997         1
500000         2
517895         1
579000         1
585000         1
599000         1
600000         2
619000         1
650000         1
700000         1
725000         1
745000         2
780000         1
820000         1
849000         1
911911         1
999990         1
999999        13
1000000        5
1010010        1
1111111        2
1234566        1
1250000        2
1300000        1
1600000        2
2795000        1
2995000        1
3890000        1
3895000        1
9999999        3
10000000       8
10010011       1
11111111      10
12345678       9
14000500       1
27322222       1
32545461       1
74185296       1
99000000       1
99999999      15
2147483647     1
Name: count, dtype: int64

In [59]:
pd.set_option("display.max_rows", 200)

In [62]:
print((autos["price"] > 200000).sum())
print((autos["price"] > 350000).sum())
print((autos["price"] > 500000).sum())
print((autos["price"] > 1000000).sum())

170
115
100
65

In [63]:
autos = autos[autos['price'].between(100, 350000)]

In [64]:
autos['price'].describe()

count   358,087.00
mean      5,940.32
std       8,883.92
min         100.00
25%       1,290.00
50%       3,100.00
75%       7,500.00
max     350,000.00
Name: price, dtype: float64